In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import datetime as dt
# import matplotlib.pyplot as plt

In [6]:
p = Path("C:/Users/k/Desktop/GitHub/GPS_transport/")

aug_data = pd.read_hdf(p / "processed_data" / "aug_all.h5", key="aug")
segments = pd.read_csv(p / "input_data" / "python" / "segments.csv")
markers = pd.read_csv(p / "input_data" / "python" / "markers.csv")

In [7]:
# disregarding dir = 2 data
aug_data = aug_data.loc[aug_data["dir"] == 1]

In [8]:
time_bin = "30T"
aug_data = aug_data.groupby("segment_id").apply(
                                            lambda x: x.set_index("aug_time")["speed"].resample("30T").mean()
                                            )

In [9]:
aug_data = aug_data.reset_index()
aug_data

        segment_id            aug_time      speed
0                2 2019-12-02 01:30:00        NaN
1                2 2019-12-02 02:00:00  77.623712
2                2 2019-12-02 02:30:00        NaN
3                2 2019-12-02 03:00:00  71.669432
4                2 2019-12-02 03:30:00  78.413552
...            ...                 ...        ...
421596         315 2019-12-29 21:30:00        NaN
421597         315 2019-12-29 22:00:00        NaN
421598         315 2019-12-29 22:30:00        NaN
421599         315 2019-12-29 23:00:00        NaN
421600         315 2019-12-29 23:30:00        NaN

[421601 rows x 3 columns]

In [10]:
# aug_data = pd.pivot_table(aug_data.groupby("segment_id").get_group(2),
#               values="speed", columns = "segment_id",
#               index="aug_time")

In [11]:
df_list = [pd.pivot_table(group_data, values="speed", columns="segment_id", index="aug_time") for _, group_data in aug_data.groupby("segment_id")]

In [35]:
segment_speed = pd.concat(df_list, axis=1)

In [36]:
segment_speed.head(20)

segment_id,2,3,4,5,6,7,8,9,10,11,...,305,306,307,308,309,310,311,312,313,314
aug_time,,,,,,,,,,,,,,,,,,,,,
2019-12-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.939214,67.611570,57.595372,57.941931,64.948077,65.306453,62.287803,53.313351,52.208248,NaN
2019-12-02 00:30:00,NaN,NaN,NaN,78.114308,78.114313,78.114310,78.114308,78.114312,78.114308,78.114312,...,89.616827,66.941322,45.046603,45.046591,66.874943,70.454603,67.980846,NaN,NaN,NaN
2019-12-02 01:00:00,NaN,NaN,63.649183,63.649178,63.649182,63.649179,63.649178,63.649178,63.649173,63.649185,...,83.667006,62.361965,52.677745,53.150151,63.315213,68.151850,65.168314,67.442283,67.012231,NaN
2019-12-02 01:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79.850856,48.320638,37.239151,37.389399,49.014961,55.999824,50.013741,42.054921,45.592969,NaN
2019-12-02 02:00:00,77.623712,78.227726,78.644003,83.842044,83.842051,83.842052,83.842043,83.842052,83.842051,83.842056,...,85.844999,67.941683,54.952200,54.952198,65.755533,70.162872,64.961279,65.534180,56.982176,NaN
2019-12-02 02:30:00,NaN,NaN,76.875542,76.875538,76.875533,76.875546,76.875536,76.875535,76.875539,76.875552,...,97.208354,82.852604,73.851411,73.851380,74.978190,68.905605,55.991171,59.637488,59.789370,30.957268
2019-12-02 03:00:00,71.669432,68.566929,69.064156,72.513460,72.513457,72.513464,72.513459,72.513461,72.513457,72.513462,...,86.668752,56.285975,38.776027,41.085840,52.078706,53.892691,40.495882,32.241927,36.394445,57.697538
2019-12-02 03:30:00,78.413552,67.534986,74.055342,77.782527,77.782523,77.782530,82.753348,84.505717,84.505723,84.505720,...,72.351037,57.414714,38.317557,43.724966,54.627970,45.606737,41.529032,38.843384,44.970000,NaN
2019-12-02 04:00:00,54.929031,40.230907,39.939025,42.712396,42.712396,42.712396,43.523434,43.578012,42.295811,42.975253,...,80.154240,63.052335,39.905109,41.573519,50.084052,50.950179,36.987244,22.810666,34.443782,NaN
2019-12-02 04:30:00,45.600309,35.687239,44.436296,46.968557,46.968557,46.968556,47.776940,49.696530,49.696530,49.696531,...,78.244623,57.151989,47.913309,47.156522,52.190310,52.396242,35.591000,24.196970,36.429379,29.950866
2019-12-02 05:00:00,24.512979,23.675951,32.336415,33.717794,33.717794,33.717794,33.584291,33.451122,33.451122,33.451122,...,86.464042,63.576118,50.146117,50.028196,58.539758,57.147467,38.513515,27.841882,36.909415,42.089411
2019-12-02 05:30:00,36.342729,31.664892,28.916342,29.356778,29.356778,29.356778,29.180339,29.233974,29.169579,29.377534,...,85.258581,48.582046,34.894618,36.388250,48.943393,55.689460,38.848994,26.698025,33.079166,NaN
2019-12-02 06:00:00,28.502127,22.529415,38.696131,42.002309,42.002309,41.915965,43.609881,45.103875,43.688213,43.894516,...,81.810527,61.171406,45.546997,47.011199,52.402632,54.138057,36.442005,27.794714,37.690266,33.001332
2019-12-02 06:30:00,56.561234,56.763584,58.444606,58.691439,58.691439,58.244995,58.510045,58.691052,58.691051,58.691051,...,83.854352,57.040638,51.024684,48.640711,52.593777,52.227808,33.350790,20.915998,29.546347,49.465330
2019-12-02 07:00:00,60.792206,60.541085,62.926282,63.210781,63.210780,63.210780,63.109651,62.955386,62.955384,62.955385,...,88.139989,59.085142,50.963936,50.464217,57.226289,56.166729,34.335491,19.679499,35.444284,40.415371
2019-12-02 07:30:00,59.308974,59.110856,59.557302,59.981997,59.981996,59.981996,60.285518,60.680692,59.682355,59.915575,...,76.683614,46.756082,37.064286,40.149240,50.593318,51.552730,31.504029,15.171822,32.211856,26.906450
2019-12-02 08:00:00,62.763178,58.198147,57.724873,57.873808,57.873807,58.377334,58.902322,59.365409,59.547845,59.547845,...,81.686689,50.875883,45.360411,47.698687,54.136763,53.547962,29.513912,20.640949,29.868154,40.471663
2019-12-02 08:30:00,57.803406,57.092615,57.987089,57.747495,57.747495,57.212508,57.197989,57.278525,57.554820,58.134905,...,78.789735,57.650485,46.645779,47.304764,53.625899,54.429004,27.387582,21.863364,32.787494,31.507895
2019-12-02 09:00:00,55.656604,55.104560,56.096301,55.436837,55.436838,55.118191,55.254197,55.272475,56.275148,56.163092,...,79.150105,57.759101,47.986292,48.064066,51.688209,50.019422,30.462704,19.412254,33.145952,28.553202
2019-12-02 09:30:00,62.221995,58.150220,60.008948,60.213984,60.213986,60.585883,60.585882,58.643861,56.335417,56.949860,...,82.974799,51.124235,42.934254,44.599617,55.854322,58.618194,32.341461,23.983771,35.110922,NaN

In [39]:
segment_speed = pd.merge(segment_speed.T, segments[["segment_id","calc_length"]], on="segment_id").set_index("segment_id")

In [41]:
segment_speed = segment_speed.T

In [44]:
segment_speed.columns = pd.to_numeric(segment_speed.columns, downcast="integer")

In [46]:
segment_speed

segment_id,2,3,4,5,6,7,8,9,10,11,...,305,306,307,308,309,310,311,312,313,314
2019-12-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.939214,67.611570,57.595372,57.941931,64.948077,65.306453,62.287803,53.313351,52.208248,NaN
2019-12-02 00:30:00,NaN,NaN,NaN,78.114308,78.114313,78.114310,78.114308,78.114312,78.114308,78.114312,...,89.616827,66.941322,45.046603,45.046591,66.874943,70.454603,67.980846,NaN,NaN,NaN
2019-12-02 01:00:00,NaN,NaN,63.649183,63.649178,63.649182,63.649179,63.649178,63.649178,63.649173,63.649185,...,83.667006,62.361965,52.677745,53.150151,63.315213,68.151850,65.168314,67.442283,67.012231,NaN
2019-12-02 01:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79.850856,48.320638,37.239151,37.389399,49.014961,55.999824,50.013741,42.054921,45.592969,NaN
2019-12-02 02:00:00,77.623712,78.227726,78.644003,83.842044,83.842051,83.842052,83.842043,83.842052,83.842051,83.842056,...,85.844999,67.941683,54.952200,54.952198,65.755533,70.162872,64.961279,65.534180,56.982176,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-29 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.431693,59.254734,44.733029,44.733033,53.490857,58.718982,42.508104,17.671287,28.925864,27.854566
2019-12-29 22:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.303461,58.302243,47.750253,49.552260,54.413482,54.652647,46.389947,23.581581,36.409298,49.361933
2019-12-29 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78.332984,69.714537,63.114256,64.317845,65.299059,65.864844,54.817467,56.744894,57.535665,NaN
2019-12-29 23:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.114919,63.470454,57.127940,57.042229,59.185666,57.643867,40.491893,39.092194,43.767631,66.595202
calc_length,77.052771,96.801784,19.202759,60.207445,77.032118,90.554982,89.721622,98.650112,51.912369,45.893105,...,339.219513,639.263008,9.369326,11.462039,272.481426,9.589032,168.122246,53.522976,36.625440,71.333030

In [48]:
segment_speed.to_excel("segment_speed.xlsx")